# Site
name: "IT Tech Hub"
title: "IT Tech Hub"
description: "it 기술을 다루는 블로그입니다."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: ''
disqus: 'x2ever'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  IT Tech Hub:
    name: IT Tech Hub
    display_name: IT Tech Hub
    gravatar: ''
    email: it.techub01@gmail.com
    web: https://github.com/it-techub
    github: https://github.com/it-techub
    description: "it 기술을 다루는 사람입니다."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
